### ISSUE TITLE
C2664

### ISSUE THREAD

**Issue by bejucoo** [wearenocomputer/ofxGSVPointCloud#1]
Hello, I have a problema with the Project when I try to run it but I don't know how to fix it.

![captura](https://user-images.githubusercontent.com/19770567/27013925-f324675a-4eb2-11e7-92fd-7fb4b03ec258.PNG)

Could you help me?

**Comment by Hoodab** [comment]
hello, I have the same problem and couldn'nt fix it . Did you ?

**Comment by bejucoo** [comment]
@Hoodab Hello, No, I tried renaming the function, deleting the "." and deleting "depthimage" but nothing works. Let's hope @wearenocomputer can help us.

**Comment by wearenocomputer** [comment]
Can you try to do this:

 depthmapimage.setFromPixels(depthPixels);

**Comment by wearenocomputer** [comment]
Hi everybody, it seems that works fine. It had something to do with a newer version of openFrameWorks

**Comment by bejucoo** [comment]
Hello, thank you for answering. It worked but now I have a problema with the OBJ and I don't really know how to fix it. Sorry for reopening this...
![2](https://user-images.githubusercontent.com/19770567/27742386-0a16d2b6-5d7e-11e7-965c-52d7207bbe5a.PNG)

**Comment by wearenocomputer** [comment]
Hi, this is probably related to zlib.
I have added zlib binaries for Windows 64 bit release.

What you need to do is:
1. add the include folder for zlib to the additional include directories folder.
You can do this in the project properties under C/C++ general 
2. Add the zlibwapi.lib file to the additional dependencies
You can find this in the project properties under Linker -> all options (at the the top)
Just add the name there just this  zlibwapi.lib
You do not have to add a path or anything here
3. Add the library path to additional library directories in Linker -> General
4. Make sure you build as 64bit Release
5. Make sure you copy the zlibwapi.dll file to the data folder in the bin folder.
