### ISSUE TITLE
Urls out of date?

### ISSUE THREAD

**Issue by YamamotoSayaka** [wearenocomputer/ofxGSVPointCloud#2]
Hi, thanks for sharing this nice code.
However the urls seems to be out of date now. I cannot get access to the panorama image or depth map from google. Can you update it?

**Comment by wearenocomputer** [comment]
They still seem to work fine:

http://maps.google.com/cbk?output=xml&ll=40.7625000,-73.9741670&dm=1

http://maps.google.com/cbk?output=tile&panoid=03s2pUakx4X6Whp_NUDo0Q&zoom=0&x=0&y=0
